[FLOW-117] Separate command into smaller steps (#3)
* Add interate and counter

* Add steps

* Complete post command

* Remove echos

* Fix tests

* Separate command into smaller steps

* Remove sample file

* Move error to reporting step

* Script improvements with arrays

* Interpolate PREFIX_ENTRIES

* Update README to tapendium example

* [FLOW-112] Add debug output

diff --git a/hooks/post-command b/hooks/post-command
--- a/hooks/post-command
+++ b/hooks/post-command
@@ -7,123 +7,200 @@ CWD="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
 # shellcheck source=lib/shared.sh
 . "$CWD/../lib/shared.sh"
 
-entries=("--entries")
-args=()
-entry_count=0
-entry=()
+PREFIX="BUILDKITE_PLUGIN_AWS_PUT_EVENT_"
+PREFIX_ENTRIES="${PREFIX}ENTRIES_"
+declare -A ENTRIES
+ENTRIES_SIZE=0
 
-[ -z "$BUILDKITE_PLUGIN_AWS_PUT_EVENT_ENTRIES_0_SOURCE" ] && {
-  echo "At least one entry needs to be defined" 1>&2
+# interate and ENTRIES_SIZE 
+while IFS='=' read -r name _; do
+  [[ $name =~ .*([0-9]) ]]
+  ENTRIES_INDEX=${BASH_REMATCH[1]}
+  ENTRY_VAR_NAME="ENTRY_${ENTRIES_INDEX}"
+  declare "ENTRY_ARG_${COUNTER}=''"
+  [ -z "${!ENTRY_VAR_NAME}" ] && {
+    export ENTRY_${ENTRIES_INDEX}=0
+  }
+  ENTRIES_SIZE=$(( ENTRIES_SIZE >= ENTRIES_INDEX + 1 ? ENTRIES_SIZE : ENTRIES_INDEX + 1 ))
+done < <(env | sort | grep "^${PREFIX_ENTRIES}[0-9]")
+
+echo [INFO] ENTRIES_SIZE $ENTRIES_SIZE
+
+for (( COUNTER=0; COUNTER<=$ENTRIES_SIZE-1; COUNTER++ ))
+do
+  NUMBERED_PREFIX="${PREFIX_ENTRIES}${COUNTER}_"
+  ENTRY_DETAIL="${NUMBERED_PREFIX}DETAIL"
+  ENTRY_DETAIL_ENV="${NUMBERED_PREFIX}DETAIL_ENV"
+  ENTRY_SOURCE="${NUMBERED_PREFIX}SOURCE"
+  ENTRY_RESOURCES="${NUMBERED_PREFIX}RESOURCES"
+  ENTRY_TRACE_HEADER="${NUMBERED_PREFIX}TRACE_HEADER"
+  ENTRY_DETAIL_TYPE="${NUMBERED_PREFIX}DETAIL_TYPE"
+  ENTRY_EVENT_BUS_NAME="${NUMBERED_PREFIX}EVENT_BUS_NAME"
+  export ENTRY_VALIDATE_${COUNTER}=31 #11111
+
+  if [ -n "${!ENTRY_DETAIL_ENV}" ]
+  then
+    # assign to detail
+    ENTRY_DETAIL_ENV_NAME=${!ENTRY_DETAIL_ENV}
+    export ${NUMBERED_PREFIX}DETAIL="${!ENTRY_DETAIL_ENV_NAME}"
+  fi
+
+  if [ -z "${!ENTRY_DETAIL}" ]
+  then
+    export ENTRY_VALIDATE_${COUNTER}=$((ENTRY_VALIDATE_${COUNTER} ^ 1))
+  else
+    ! is_valid_json "${!ENTRY_DETAIL}" && {
+      export ENTRY_VALIDATE_${COUNTER}=$((ENTRY_VALIDATE_${COUNTER} ^ 2))
+    }
+    ENTRIES[$COUNTER,0]="Detail=$( echo ${!ENTRY_DETAIL} | jq -R )"
+  fi
+
+  if [ -z "${!ENTRY_SOURCE}" ]
+  then
+    export ENTRY_VALIDATE_${COUNTER}=$((ENTRY_VALIDATE_${COUNTER} ^ 4))
+  else
+    ENTRIES[$COUNTER,1]="Source=${!ENTRY_SOURCE}"
+  fi
+
+  if [ -z "${!ENTRY_DETAIL_TYPE}" ]
+  then
+    export ENTRY_VALIDATE_${COUNTER}=$((ENTRY_VALIDATE_${COUNTER} ^ 8))
+  else
+    ENTRIES[$COUNTER,2]="DetailType=${!ENTRY_DETAIL_TYPE}"
+  fi
+
+  if [ -z "${!ENTRY_EVENT_BUS_NAME}" ]
+  then
+    export ENTRY_VALIDATE_${COUNTER}=$((ENTRY_VALIDATE_${COUNTER} ^ 16))
+  else
+    ENTRIES[$COUNTER,3]="EventBusName=${!ENTRY_EVENT_BUS_NAME}"
+  fi
+
+  if [ -n "${!ENTRY_RESOURCES}" ]
+  then
+    ENTRIES[$COUNTER,4]="Resources=${!ENTRY_RESOURCES}"
+  fi
+
+  if [ -n "${!ENTRY_TRACE_HEADER}" ]
+  then
+    ENTRIES[$COUNTER,5]="TraceHeader=${!ENTRY_TRACE_HEADER}"
+  fi
+
+done
+
+VALID=1
+for (( COUNTER=0; COUNTER<=$ENTRIES_SIZE-1; COUNTER++ ))
+do
+  if [ $(( ENTRY_VALIDATE_$COUNTER )) -eq 31 ]; then
+    continue
+  fi
+
+  VALID=0
+
+  [ $(( ENTRY_VALIDATE_$COUNTER & 1 )) -eq 0 ] && {
+    echo "[ERROR] Entry[$COUNTER]: detail or detail-env not defined." 
+  }
+
+  export ENTRY_VALIDATE_$COUNTER=$((ENTRY_VALIDATE_$COUNTER >> 1))
+
+  [ $(( ENTRY_VALIDATE_$COUNTER & 1 )) -eq 0 ] && {
+    echo "[ERROR] Entry[$COUNTER]: detail has invalid json" 
+  }
+
+  export ENTRY_VALIDATE_$COUNTER=$((ENTRY_VALIDATE_$COUNTER >> 1))
+
+  [ $(( ENTRY_VALIDATE_$COUNTER & 1 )) -eq 0 ] && {
+    echo "[ERROR] Entry[$COUNTER]: source not defined." 
+  }
+
+  export ENTRY_VALIDATE_$COUNTER=$((ENTRY_VALIDATE_$COUNTER >> 1))
+
+  [ $(( ENTRY_VALIDATE_$COUNTER & 1 )) -eq 0 ] && {
+    echo "[ERROR] Entry[$COUNTER]: detail-type not defined." 
+  }
+
+  export ENTRY_VALIDATE_$COUNTER=$((ENTRY_VALIDATE_$COUNTER >> 1))
+
+  [ $(( ENTRY_VALIDATE_$COUNTER & 1 )) -eq 0 ] && {
+    echo "[ERROR] Entry[$COUNTER]: event-bus-name not defined." 
+  }
+done
+
+[ $ENTRIES_SIZE -eq 0 ] && {
+  # warn and let it pass
+  echo "[WARNING] At least one entry needs to be defined" 1>&2
   exit 1
 }
 
+[ $VALID -eq 0 ] && {
+  echo "[ERROR] Process failed with errors."
+  exit 2
+}
+
+ENTRIES_ARG="--entries"
+for (( COUNTER=0; COUNTER<=$ENTRIES_SIZE-1; COUNTER++ ))
+do
+  if [ -n "${ENTRIES[$COUNTER,0]}" ]
+  then
+    ENTRIES_ARG+=" ${ENTRIES[$COUNTER,0]}"
+  fi
+  
+  if [ -n "${ENTRIES[$COUNTER,1]}" ]
+  then
+    ENTRIES_ARG+=",${ENTRIES[$COUNTER,1]}"
+  fi
+
+  if [ -n "${ENTRIES[$COUNTER,2]}" ]
+  then
+    ENTRIES_ARG+=",${ENTRIES[$COUNTER,2]}"
+  fi
+
+  if [ -n "${ENTRIES[$COUNTER,3]}" ]
+  then
+    ENTRIES_ARG+=",${ENTRIES[$COUNTER,3]}"
+  fi
+
+  if [ -n "${ENTRIES[$COUNTER,4]}" ]
+  then
+    ENTRIES_ARG+=",${ENTRIES[$COUNTER,4]}"
+  fi
+
+  if [ -n "${ENTRIES[$COUNTER,5]}" ]
+  then
+    ENTRIES_ARG+=",${ENTRIES[$COUNTER,5]}"
+  fi
+done
+
+ADDITIONAL_ARGS=()
 while IFS='=' read -r name _; do
-  if [[ $name =~ ^(BUILDKITE_PLUGIN_AWS_PUT_EVENT_ENTRIES_[0-9]+) ]]; then
-    prefix="BUILDKITE_PLUGIN_AWS_PUT_EVENT_ENTRIES_${entry_count}_"
-    detail_arg="${prefix}DETAIL"
-    detail_env_arg="${prefix}DETAIL_ENV"
-    source_arg="${prefix}SOURCE"
-    detail_type_arg="${prefix}DETAIL_TYPE"
-    event_bus_name_arg="${prefix}EVENT_BUS_NAME"
-
-    [ -z "${!detail_arg}" ] && [ -z "${!detail_env_arg}" ] && {
-      echo "entries > detail or detail-env not defined. Exiting" 1>&2
-      exit 1
-    }
-
-    [ -z "${!source_arg}" ] && {
-      echo "entries > source not defined. Exiting" 1>&2
-      exit 1
-    }
-
-    [ -z "${!detail_type_arg}" ] && {
-      echo "entries > detail-type not defined. Exiting" 1>&2
-      exit 1
-    }
-
-    [ -z "${!event_bus_name_arg}" ] && {
-      echo "entries > event-bus-name not defined. Exiting" 1>&2
-      exit 1
-    }
-
-    # if entry increments, reset the entry and increment the counter
-    if ! [[ $name =~ (${entry_count}) ]]; then
-      entry_join=$(IFS=, ; echo "${entry[*]}")
-      entries+=("$entry_join")
-      entry_count=$((entry_count+1))
-      entry=()
-    fi
-
-    if [[ $name =~ (DETAIL_ENV)$ ]] ; then
-      detail_env_key="${!name}"
-      detail_env_val="${!detail_env_key}"
-      entry+=("Detail=${detail_env_val}")
-    elif [[ $name =~ (DETAIL)$ ]]; then
-      entry+=("Detail=${!name}")
-    fi
-
-    if [[ $name =~ (SOURCE)$ ]]; then
-      entry+=("Source=${!name}")
-    fi
-    if [[ $name =~ (RESOURCES)$ ]]; then
-      entry+=("Resources=${!name}")
-    fi
-    if [[ $name =~ (DETAIL_TYPE)$ ]]; then
-      entry+=("DetailType=${!name}")
-    fi
-    if [[ $name =~ (EVENT_BUS_NAME)$ ]]; then
-      entry+=("EventBusName=${!name}")
-    fi
-    if [[ $name =~ (TRACE_HEADER)$ ]]; then
-      entry+=("TraceHeader=${!name}")
-    fi
+  if [[ $name =~ (ENDPOINT_URL)$ ]]; then
+    ADDITIONAL_ARGS+=("--endpoint-url" "${!name}")
   fi
 
-  if [[ $name =~ ^(BUILDKITE_PLUGIN_AWS_PUT_ENDPOINT_URL) ]]; then
-    args+=("--endpoint-url" "${!name}")
+  if [[ $name =~ (ENDPOINT_ID)$ ]]; then
+    ADDITIONAL_ARGS+=("--endpoint-id" "${!name}")
   fi
 
-  if [[ $name =~ ^(BUILDKITE_PLUGIN_AWS_PUT_EVENT_ENDPOINT_ID) ]]; then
-    args+=("--endpoint-id" "${!name}")
+  if [[ $name =~ (CLI_INPUT_JSON)$ ]]; then
+    ADDITIONAL_ARGS+=("--cli-input-json" "${!name}")
   fi
 
-  if [[ $name =~ ^(BUILDKITE_PLUGIN_AWS_PUT_EVENT_CLI_INPUT_JSON) ]]; then
-    args+=("--cli-input-json" "${!name}")
+  if [[ $name =~ (GENERATE_CLI_SKELETON)$ ]]; then
+    ADDITIONAL_ARGS+=("--generate-cli-skeleton" "${!name}")
   fi
 
-  if [[ $name =~ ^(BUILDKITE_PLUGIN_AWS_PUT_EVENT_GENERATE_CLI_SKELETON) ]]; then
-    args+=("--generate-cli-skeleton" "${!name}")
+  if [[ $name =~ (REGION)$ ]]; then
+    ADDITIONAL_ARGS+=("--region" "${!name}")
   fi
 
-  if [[ $name =~ ^(BUILDKITE_PLUGIN_AWS_PUT_EVENT_REGION) ]]; then
-    args+=("--region" "${!name}")
+  if [[ $name =~ (DEBUG)$ ]]; then
+    ADDITIONAL_ARGS+=("--debug")
   fi
+done < <(env | sort | grep "^${PREFIX}")
 
-  if [[ $name =~ ^(BUILDKITE_PLUGIN_AWS_PUT_EVENT_DEBUG) ]]; then
-    args+=("--debug")
-  fi
-done < <(env | sort)
+echo "[PUBLISH EVENT]"
+echo "[RNNNING COMMAND]"
 
-# append last entry
-entry_join=$(IFS=, ; echo "${entry[*]}")
-entries+=("$entry_join")
-
-# debugger
-# [[ "${entries[@]}" != "Source" ]] && {
-#   echo "$entry_join"
-#   printf "%q " "${entries[@]}"
-#   echo
-#   printf "%q " "${args[@]}"
-#   echo "\ndebug in testing"
-#   exit 1;
-# }
-
-echo "--- Sending event"
-echo -ne '\033[90m$\033[0m aws events put-events ' >&2
-
-printf "%q " "${entries[@]}"
-printf "%q " "${args[@]}"
-echo
-
-put_events "${entries[@]}" "${args[@]}"
-
+set -x
+aws events put-events "$ENTRIES_ARG" "${ADDITIONAL_ARGS[@]}" --output json
+set +x
