Script improvements with arrays

diff --git a/hooks/post-command b/hooks/post-command
--- a/hooks/post-command
+++ b/hooks/post-command
@@ -7,6 +7,9 @@ CWD="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
 # shellcheck source=lib/shared.sh
 . "$CWD/../lib/shared.sh"
 
+PREFIX="BUILDKITE_PLUGIN_AWS_PUT_EVENT_"
+PREFIX_ENTRIES="BUILDKITE_PLUGIN_AWS_PUT_EVENT_ENTRIES_"
+declare -A ENTRIES
 ENTRIES_SIZE=0
 
 # interate and ENTRIES_SIZE 
@@ -19,77 +22,114 @@ while IFS='=' read -r name _; do
     export ENTRY_${ENTRIES_INDEX}=0
   }
   ENTRIES_SIZE=$(( ENTRIES_SIZE >= ENTRIES_INDEX + 1 ? ENTRIES_SIZE : ENTRIES_INDEX + 1 ))
-done < <(env | sort | grep ^BUILDKITE_PLUGIN_AWS_PUT_EVENT_ENTRIES_[0-9])
+done < <(env | sort | grep "^${PREFIX_ENTRIES}[0-9]")
 
-# validate entries
-echo [Entries Size] $(( $ENTRIES_SIZE ))
-while IFS='=' read -r name _; do
-  [[ $name =~ .*([0-9]) ]]
-  ENTRIES_INDEX=${BASH_REMATCH[1]}
-  prefix="BUILDKITE_PLUGIN_AWS_PUT_EVENT_ENTRIES_${ENTRIES_INDEX}_"
-  detail_arg="${prefix}DETAIL"
-  detail_env_arg="${prefix}DETAIL_ENV"
-  source_arg="${prefix}SOURCE"
-  detail_type_arg="${prefix}DETAIL_TYPE"
-  event_bus_name_arg="${prefix}EVENT_BUS_NAME"
+echo [INFO] ENTRIES_SIZE $ENTRIES_SIZE
 
-  [ -z "${!detail_arg}" ] && [ -z "${!detail_env_arg}" ] && {
-    export ENTRY_${ENTRIES_INDEX}=$((ENTRY_${ENTRIES_INDEX} | 1))
-  }
-
-  [ -z "${!source_arg}" ] && {
-    export ENTRY_${ENTRIES_INDEX}=$((ENTRY_${ENTRIES_INDEX} | 2))
-  }
-
-  [ -z "${!detail_type_arg}" ] && {
-    export ENTRY_${ENTRIES_INDEX}=$((ENTRY_${ENTRIES_INDEX} | 4))
-  }
-
-  [ -z "${!event_bus_name_arg}" ] && {
-    export ENTRY_${ENTRIES_INDEX}=$((ENTRY_${ENTRIES_INDEX} | 8))
-  }
-done < <(env | sort | grep ^BUILDKITE_PLUGIN_AWS_PUT_EVENT_ENTRIES_[0-9])
-
-# Report
-COUNTER=0
-VALID=1
-while [ $COUNTER -lt $ENTRIES_SIZE ]
+for (( COUNTER=0; COUNTER<=$ENTRIES_SIZE-1; COUNTER++ ))
 do
-  ENTRY="ENTRY_$COUNTER"
-  if [ $(( ENTRY_$COUNTER )) -eq 0 ]; then
-    COUNTER=$(( $COUNTER + 1 ))
+  NUMBERED_PREFIX="${PREFIX_ENTRIES}${COUNTER}_"
+  ENTRY_DETAIL="${NUMBERED_PREFIX}DETAIL"
+  ENTRY_DETAIL_ENV="${NUMBERED_PREFIX}DETAIL_ENV"
+  ENTRY_SOURCE="${NUMBERED_PREFIX}SOURCE"
+  ENTRY_RESOURCES="${NUMBERED_PREFIX}RESOURCES"
+  ENTRY_TRACE_HEADER="${NUMBERED_PREFIX}TRACE_HEADER"
+  ENTRY_DETAIL_TYPE="${NUMBERED_PREFIX}DETAIL_TYPE"
+  ENTRY_EVENT_BUS_NAME="${NUMBERED_PREFIX}EVENT_BUS_NAME"
+  export ENTRY_VALIDATE_${COUNTER}=31 #11111
+
+  if [ -n "${!ENTRY_DETAIL_ENV}" ]
+  then
+    # assign to detail
+    ENTRY_DETAIL_ENV_NAME=${!ENTRY_DETAIL_ENV}
+    export ${NUMBERED_PREFIX}DETAIL="${!ENTRY_DETAIL_ENV_NAME}"
+  fi
+
+  if [ -z "${!ENTRY_DETAIL}" ]
+  then
+    export ENTRY_VALIDATE_${COUNTER}=$((ENTRY_VALIDATE_${COUNTER} ^ 1))
+  else
+    ! is_valid_json "${!ENTRY_DETAIL}" && {
+      export ENTRY_VALIDATE_${COUNTER}=$((ENTRY_VALIDATE_${COUNTER} ^ 2))
+    }
+    ENTRIES[$COUNTER,0]="Detail=${!ENTRY_DETAIL}"
+  fi
+
+  if [ -z "${!ENTRY_SOURCE}" ]
+  then
+    export ENTRY_VALIDATE_${COUNTER}=$((ENTRY_VALIDATE_${COUNTER} ^ 4))
+  else
+    ENTRIES[$COUNTER,1]="Source=${!ENTRY_SOURCE}"
+  fi
+
+  if [ -z "${!ENTRY_DETAIL_TYPE}" ]
+  then
+    export ENTRY_VALIDATE_${COUNTER}=$((ENTRY_VALIDATE_${COUNTER} ^ 8))
+  else
+    ENTRIES[$COUNTER,2]="DetailType=${!ENTRY_DETAIL_TYPE}"
+  fi
+
+  if [ -z "${!ENTRY_EVENT_BUS_NAME}" ]
+  then
+    export ENTRY_VALIDATE_${COUNTER}=$((ENTRY_VALIDATE_${COUNTER} ^ 16))
+  else
+    ENTRIES[$COUNTER,3]="EventBusName=${!ENTRY_EVENT_BUS_NAME}"
+  fi
+
+  if [ -n "${!ENTRY_RESOURCES}" ]
+  then
+    ENTRIES[$COUNTER,4]="Resources=${!ENTRY_RESOURCES}"
+  fi
+
+  if [ -n "${!ENTRY_TRACE_HEADER}" ]
+  then
+    ENTRIES[$COUNTER,5]="TraceHeader=${!ENTRY_TRACE_HEADER}"
+  fi
+
+done
+
+VALID=1
+for (( COUNTER=0; COUNTER<=$ENTRIES_SIZE-1; COUNTER++ ))
+do
+  if [ $(( ENTRY_VALIDATE_$COUNTER )) -eq 31 ]; then
     continue
   fi
+
   VALID=0
 
-  [ $(( ENTRY_$COUNTER & 1 )) -eq 1 ] && {
+  [ $(( ENTRY_VALIDATE_$COUNTER & 1 )) -eq 0 ] && {
     echo "[ERROR] Entry[$COUNTER]: detail or detail-env not defined." 
   }
 
-  export ENTRY_$COUNTER=$((ENTRY_$COUNTER >> 1))
+  export ENTRY_VALIDATE_$COUNTER=$((ENTRY_VALIDATE_$COUNTER >> 1))
 
-  [ $(( ENTRY_$COUNTER & 1 )) -eq 1 ] && {
+  [ $(( ENTRY_VALIDATE_$COUNTER & 1 )) -eq 0 ] && {
+    echo "[ERROR] Entry[$COUNTER]: detail has invalid json" 
+  }
+
+  export ENTRY_VALIDATE_$COUNTER=$((ENTRY_VALIDATE_$COUNTER >> 1))
+
+  [ $(( ENTRY_VALIDATE_$COUNTER & 1 )) -eq 0 ] && {
     echo "[ERROR] Entry[$COUNTER]: source not defined." 
   }
 
-  export ENTRY_$COUNTER=$((ENTRY_$COUNTER >> 1))
+  export ENTRY_VALIDATE_$COUNTER=$((ENTRY_VALIDATE_$COUNTER >> 1))
 
-  [ $(( ENTRY_$COUNTER & 1 )) -eq 1 ] && {
+  [ $(( ENTRY_VALIDATE_$COUNTER & 1 )) -eq 0 ] && {
     echo "[ERROR] Entry[$COUNTER]: detail-type not defined." 
   }
 
-  export ENTRY_$COUNTER=$((ENTRY_$COUNTER >> 1))
+  export ENTRY_VALIDATE_$COUNTER=$((ENTRY_VALIDATE_$COUNTER >> 1))
 
-  [ $(( ENTRY_$COUNTER & 1 )) -eq 1 ] && {
+  [ $(( ENTRY_VALIDATE_$COUNTER & 1 )) -eq 0 ] && {
     echo "[ERROR] Entry[$COUNTER]: event-bus-name not defined." 
   }
-
-  COUNTER=$(( $COUNTER + 1 ))
 done
 
 [ $ENTRIES_SIZE -eq 0 ] && {
-  echo "[ERROR] At least one entry needs to be defined" 1>&2
-  VALID=0
+  # warn and let it pass
+  echo "[WARNING] At least one entry needs to be defined" 1>&2
+  exit 1
 }
 
 [ $VALID -eq 0 ] && {
@@ -97,80 +137,69 @@ done
   exit 1
 }
 
-while IFS='=' read -r name _; do
-  [[ $name =~ .*([0-9]) ]]
-  ENTRIES_INDEX=${BASH_REMATCH[1]}
-  DETAIL_ENV="BUILDKITE_PLUGIN_AWS_PUT_EVENT_ENTRIES_${ENTRIES_INDEX}_DETAIL_ENV"
-  ENTRY_ARG_NAME="ENTRY_ARG_${ENTRIES_INDEX}"
-  ENTRY_ARG=${!ENTRY_ARG_NAME}
-
-  if [[ -n $DETAIL_ENV ]] && [[ $name =~ (DETAIL_ENV)$ ]] && [[ $ENTRY_ARG != *"Detail"* ]]; then
-    detail_env_key="${!name}"
-    detail_env_val="${!detail_env_key}"
-    eval "ENTRY_ARG_${ENTRIES_INDEX}+=,Detail=${detail_env_val}"
+ENTRIES_ARG="--entries"
+for (( COUNTER=0; COUNTER<=$ENTRIES_SIZE-1; COUNTER++ ))
+do
+  if [ -n "${ENTRIES[$COUNTER,0]}" ]
+  then
+    ENTRIES_ARG+=" ${ENTRIES[$COUNTER,0]}"
+  fi
+  
+  if [ -n "${ENTRIES[$COUNTER,1]}" ]
+  then
+    ENTRIES_ARG+=",${ENTRIES[$COUNTER,1]}"
   fi
 
-  if [[ $name =~ (DETAIL)$ ]] && [[ $ENTRY_ARG != *"Detail"* ]]; then
-    eval "ENTRY_ARG_${ENTRIES_INDEX}+=,Detail=$(echo ${!name} | jq -R)"
+  if [ -n "${ENTRIES[$COUNTER,2]}" ]
+  then
+    ENTRIES_ARG+=",${ENTRIES[$COUNTER,2]}"
   fi
 
-  if [[ $name =~ (SOURCE)$ ]]; then
-    eval "ENTRY_ARG_${ENTRIES_INDEX}+=,Source=${!name}"
+  if [ -n "${ENTRIES[$COUNTER,3]}" ]
+  then
+    ENTRIES_ARG+=",${ENTRIES[$COUNTER,3]}"
   fi
-  if [[ $name =~ (RESOURCES)$ ]]; then
-    eval "ENTRY_ARG_${ENTRIES_INDEX}+=,Resources=${!name}"
+
+  if [ -n "${ENTRIES[$COUNTER,4]}" ]
+  then
+    ENTRIES_ARG+=",${ENTRIES[$COUNTER,4]}"
   fi
-  if [[ $name =~ (DETAIL_TYPE)$ ]]; then
-    eval "ENTRY_ARG_${ENTRIES_INDEX}+=,DetailType=${!name}"
+
+  if [ -n "${ENTRIES[$COUNTER,5]}" ]
+  then
+    ENTRIES_ARG+=",${ENTRIES[$COUNTER,5]}"
   fi
-  if [[ $name =~ (EVENT_BUS_NAME)$ ]]; then
-    eval "ENTRY_ARG_${ENTRIES_INDEX}+=,EventBusName=${!name}"
-  fi
-  if [[ $name =~ (TRACE_HEADER)$ ]]; then
-    eval "ENTRY_ARG_${ENTRIES_INDEX}+=,TraceHeader=${!name}"
-  fi
-done < <(env | sort | grep ^BUILDKITE_PLUGIN_AWS_PUT_EVENT_ENTRIES_[0-9])
+done
 
 ADDITIONAL_ARGS=()
 while IFS='=' read -r name _; do
-  if [[ $name =~ ^(BUILDKITE_PLUGIN_AWS_PUT_ENDPOINT_URL) ]]; then
+  if [[ $name =~ (ENDPOINT_URL)$ ]]; then
     ADDITIONAL_ARGS+=("--endpoint-url" "${!name}")
   fi
 
-  if [[ $name =~ ^(BUILDKITE_PLUGIN_AWS_PUT_EVENT_ENDPOINT_ID) ]]; then
+  if [[ $name =~ (ENDPOINT_ID)$ ]]; then
     ADDITIONAL_ARGS+=("--endpoint-id" "${!name}")
   fi
 
-  if [[ $name =~ ^(BUILDKITE_PLUGIN_AWS_PUT_EVENT_CLI_INPUT_JSON) ]]; then
+  if [[ $name =~ (CLI_INPUT_JSON)$ ]]; then
     ADDITIONAL_ARGS+=("--cli-input-json" "${!name}")
   fi
 
-  if [[ $name =~ ^(BUILDKITE_PLUGIN_AWS_PUT_EVENT_GENERATE_CLI_SKELETON) ]]; then
+  if [[ $name =~ (GENERATE_CLI_SKELETON)$ ]]; then
     ADDITIONAL_ARGS+=("--generate-cli-skeleton" "${!name}")
   fi
 
-  if [[ $name =~ ^(BUILDKITE_PLUGIN_AWS_PUT_EVENT_REGION) ]]; then
+  if [[ $name =~ (REGION)$ ]]; then
     ADDITIONAL_ARGS+=("--region" "${!name}")
   fi
 
-  if [[ $name =~ ^(BUILDKITE_PLUGIN_AWS_PUT_EVENT_DEBUG) ]]; then
+  if [[ $name =~ (DEBUG)$ ]]; then
     ADDITIONAL_ARGS+=("--debug")
   fi
-done < <(env | sort | grep ^BUILDKITE_PLUGIN_AWS_PUT)
-
-ASSIGN_COUNTER=0
-ENTRIES=("--entries")
-while [ $ASSIGN_COUNTER -lt $ENTRIES_SIZE ]
-do
-  ENTRY_ARG_ARR_NAME="ENTRY_ARG_$ASSIGN_COUNTER[*]"
-  ENTRY_ARG_ARR=${!ENTRY_ARG_ARR_NAME}
-  ENTRY_JOIN=$(IFS=, ; echo "${ENTRY_ARG_ARR}")
-  ENTRIES+=("${ENTRY_JOIN:1}")
-  ASSIGN_COUNTER=$(( $ASSIGN_COUNTER + 1 ))
-done
+done < <(env | sort | grep "^${PREFIX}")
 
 echo "[PUBLISH EVENT]"
 echo "[RNNNING COMMAND]"
-echo "aws events put-events" "${ENTRIES[@]}" "${ADDITIONAL_ARGS[@]}"
+echo "aws events put-events" "$ENTRIES_ARG" "${ADDITIONAL_ARGS[@]}"
 
-put_events "${ENTRIES[@]}" "${ADDITIONAL_ARGS[@]}"
+put_events "$ENTRIES_ARG" "${ADDITIONAL_ARGS[@]}"
